### ISSUE TITLE
Nether portal glitch

### ISSUE THREAD

**Issue by SafronMC** [2pocket2edition/Nukkit#34] opened 2018-04-02 14:05 UTC
### Expected Behavior
When you go through a portal at the nether. It puts you on x8 of the coords you have. Vice versa

### Actual Behavior
Nether portal mirrors the coords regardless overworld-nether or nether-overworld. Occurs frequently now. Idk if this is being tracked.

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by Megalunchbox** [comment] 2018-04-21 21:13
now this sends you to the divided 8x coords but when you leave the nether you stay at the same nether coords

**Comment by DaMatrix** [comment] 2018-04-22 03:27
I'm still unable to reproduce this.

**Comment by Megalunchbox** [comment] 2018-04-22 03:41
just walk into a nether portal then walk out and your coords will be 8x less

**Comment by DaMatrix** [comment] 2018-04-23 00:05
I tried this about 10 times, and came out in the correct coordinates every time.

**Comment by o0ZzM4g1c** [comment] 2018-09-25 13:46
do you want a test with exact coord report ?  I'm facing this issue at all portals on x-, z0. from -5k to spawn.

**Comment by DaMatrix** [comment] 2020-01-27 10:04
Closing all issues due to pending update to NukkitX 2.0

**Closed as completed by DaMatrix** 2020-01-27 10:04 UTC
Labels: bug, priority:medium, old
